name: tugasakhir
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  firebase_analytics: ^11.1.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1
  carousel_slider: ^4.2.1

  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/logoupapp.png
    - assets/image/logoupapp2.png

flutter_icons:
  android: true
  image_path: assets/image/logoupapp.png
